/* Generated by scripts/import-portfolio-assets.mjs from E:/工作/成果. */
import type { ProjectMedia } from './projects';

export const importedProjectMedia: ProjectMedia[] = [
  {
    "slug": "daying-yongyi-hotel",
    "name": "四川 大英永逸酒店",
    "year": 2019,
    "category": "selected",
    "cover": "/portfolio/daying-yongyi-hotel/cover.webp",
    "images": [
      "/portfolio/daying-yongyi-hotel/image-01.webp",
      "/portfolio/daying-yongyi-hotel/image-02.webp",
      "/portfolio/daying-yongyi-hotel/image-03.webp",
      "/portfolio/daying-yongyi-hotel/image-04.webp",
      "/portfolio/daying-yongyi-hotel/image-05.webp",
      "/portfolio/daying-yongyi-hotel/image-06.webp",
      "/portfolio/daying-yongyi-hotel/image-07.webp",
      "/portfolio/daying-yongyi-hotel/image-08.webp",
      "/portfolio/daying-yongyi-hotel/image-09.webp",
      "/portfolio/daying-yongyi-hotel/image-10.webp",
      "/portfolio/daying-yongyi-hotel/image-11.webp",
      "/portfolio/daying-yongyi-hotel/image-12.webp",
      "/portfolio/daying-yongyi-hotel/image-13.webp",
      "/portfolio/daying-yongyi-hotel/image-14.webp",
      "/portfolio/daying-yongyi-hotel/image-15.webp",
      "/portfolio/daying-yongyi-hotel/image-16.webp",
      "/portfolio/daying-yongyi-hotel/image-17.webp"
    ],
    "plans": [],
    "heroImages": [
      "/portfolio/daying-yongyi-hotel/hero-01.webp",
      "/portfolio/daying-yongyi-hotel/hero-02.webp",
      "/portfolio/daying-yongyi-hotel/hero-03.webp"
    ]
  },
  {
    "slug": "ctn-office",
    "name": "中税网办公室",
    "year": 2023,
    "category": "selected",
    "cover": "/portfolio/ctn-office/cover.webp",
    "images": [
      "/portfolio/ctn-office/image-01.webp",
      "/portfolio/ctn-office/image-02.webp",
      "/portfolio/ctn-office/image-03.webp",
      "/portfolio/ctn-office/image-04.webp",
      "/portfolio/ctn-office/image-05.webp"
    ],
    "plans": [],
    "heroImages": [
      "/portfolio/ctn-office/hero-01.webp",
      "/portfolio/ctn-office/hero-02.webp"
    ]
  },
  {
    "slug": "tech-office",
    "name": "科技办公室",
    "year": 2024,
    "category": "selected",
    "cover": "/portfolio/tech-office/cover.webp",
    "images": [
      "/portfolio/tech-office/image-01.webp",
      "/portfolio/tech-office/image-02.webp",
      "/portfolio/tech-office/image-03.webp",
      "/portfolio/tech-office/image-04.webp",
      "/portfolio/tech-office/image-05.webp",
      "/portfolio/tech-office/image-06.webp",
      "/portfolio/tech-office/image-07.webp"
    ],
    "plans": [],
    "heroImages": [
      "/portfolio/tech-office/hero-01.webp",
      "/portfolio/tech-office/hero-02.webp"
    ]
  },
  {
    "slug": "library",
    "name": "图书馆",
    "year": 2023,
    "category": "selected",
    "cover": "/portfolio/library/cover.webp",
    "images": [
      "/portfolio/library/image-01.webp",
      "/portfolio/library/image-02.webp",
      "/portfolio/library/image-03.webp",
      "/portfolio/library/image-04.webp",
      "/portfolio/library/image-05.webp"
    ],
    "plans": [],
    "heroImages": [
      "/portfolio/library/hero-01.webp",
      "/portfolio/library/hero-02.webp"
    ]
  },
  {
    "slug": "ruigao-international",
    "name": "睿高国际",
    "year": 2023,
    "category": "selected",
    "cover": "/portfolio/ruigao-international/cover.webp",
    "images": [
      "/portfolio/ruigao-international/image-01.webp",
      "/portfolio/ruigao-international/image-02.webp",
      "/portfolio/ruigao-international/image-03.webp",
      "/portfolio/ruigao-international/image-04.webp",
      "/portfolio/ruigao-international/image-05.webp"
    ],
    "plans": [],
    "heroImages": [
      "/portfolio/ruigao-international/hero-01.webp",
      "/portfolio/ruigao-international/hero-02.webp"
    ]
  },
  {
    "slug": "rongchang-residence",
    "name": "荣昌住宅",
    "year": 2026,
    "category": "residential",
    "cover": "/portfolio/rongchang-residence/cover.webp",
    "images": [
      "/portfolio/rongchang-residence/image-01.webp",
      "/portfolio/rongchang-residence/image-02.webp",
      "/portfolio/rongchang-residence/image-03.webp",
      "/portfolio/rongchang-residence/image-04.webp",
      "/portfolio/rongchang-residence/image-05.webp",
      "/portfolio/rongchang-residence/image-06.webp",
      "/portfolio/rongchang-residence/image-07.webp",
      "/portfolio/rongchang-residence/image-08.webp",
      "/portfolio/rongchang-residence/image-09.webp"
    ],
    "plans": [
      "/portfolio/rongchang-residence/plan-01.webp"
    ],
    "heroImages": []
  },
  {
    "slug": "tianchen-villa",
    "name": "天辰雅墅",
    "year": 2025,
    "category": "residential",
    "cover": "/portfolio/tianchen-villa/cover.webp",
    "images": [
      "/portfolio/tianchen-villa/image-01.webp",
      "/portfolio/tianchen-villa/image-02.webp",
      "/portfolio/tianchen-villa/image-03.webp",
      "/portfolio/tianchen-villa/image-04.webp",
      "/portfolio/tianchen-villa/image-05.webp",
      "/portfolio/tianchen-villa/image-06.webp",
      "/portfolio/tianchen-villa/image-07.webp",
      "/portfolio/tianchen-villa/image-08.webp",
      "/portfolio/tianchen-villa/image-09.webp"
    ],
    "plans": [
      "/portfolio/tianchen-villa/plan-01.webp"
    ],
    "heroImages": []
  },
  {
    "slug": "show-flat-2025",
    "name": "样板间",
    "year": 2025,
    "category": "residential",
    "cover": "/portfolio/show-flat-2025/cover.webp",
    "images": [
      "/portfolio/show-flat-2025/image-01.webp",
      "/portfolio/show-flat-2025/image-02.webp",
      "/portfolio/show-flat-2025/image-03.webp",
      "/portfolio/show-flat-2025/image-04.webp",
      "/portfolio/show-flat-2025/image-05.webp",
      "/portfolio/show-flat-2025/image-06.webp",
      "/portfolio/show-flat-2025/image-07.webp",
      "/portfolio/show-flat-2025/image-08.webp",
      "/portfolio/show-flat-2025/image-09.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "yidun-residence",
    "name": "伊顿庄园",
    "year": 2025,
    "category": "residential",
    "cover": "/portfolio/yidun-residence/cover.webp",
    "images": [
      "/portfolio/yidun-residence/image-01.webp",
      "/portfolio/yidun-residence/image-02.webp",
      "/portfolio/yidun-residence/image-03.webp",
      "/portfolio/yidun-residence/image-04.webp",
      "/portfolio/yidun-residence/image-05.webp",
      "/portfolio/yidun-residence/image-06.webp",
      "/portfolio/yidun-residence/image-07.webp",
      "/portfolio/yidun-residence/image-08.webp",
      "/portfolio/yidun-residence/image-09.webp",
      "/portfolio/yidun-residence/image-10.webp",
      "/portfolio/yidun-residence/image-11.webp"
    ],
    "plans": [
      "/portfolio/yidun-residence/plan-01.webp"
    ],
    "heroImages": []
  },
  {
    "slug": "duplex-residence",
    "name": "跃层住宅",
    "year": 2025,
    "category": "residential",
    "cover": "/portfolio/duplex-residence/cover.webp",
    "images": [
      "/portfolio/duplex-residence/image-01.webp",
      "/portfolio/duplex-residence/image-02.webp",
      "/portfolio/duplex-residence/image-03.webp",
      "/portfolio/duplex-residence/image-04.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "house-2025",
    "name": "HUOSE",
    "year": 2025,
    "category": "residential",
    "cover": "/portfolio/house-2025/cover.webp",
    "images": [
      "/portfolio/house-2025/image-01.webp",
      "/portfolio/house-2025/image-02.webp",
      "/portfolio/house-2025/image-03.webp",
      "/portfolio/house-2025/image-04.webp",
      "/portfolio/house-2025/image-05.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "taoyuan-residence",
    "name": "桃源世家",
    "year": 2024,
    "category": "residential",
    "cover": "/portfolio/taoyuan-residence/cover.webp",
    "images": [
      "/portfolio/taoyuan-residence/image-01.webp",
      "/portfolio/taoyuan-residence/image-02.webp",
      "/portfolio/taoyuan-residence/image-03.webp",
      "/portfolio/taoyuan-residence/image-04.webp",
      "/portfolio/taoyuan-residence/image-05.webp",
      "/portfolio/taoyuan-residence/image-06.webp",
      "/portfolio/taoyuan-residence/image-07.webp",
      "/portfolio/taoyuan-residence/image-08.webp",
      "/portfolio/taoyuan-residence/image-09.webp",
      "/portfolio/taoyuan-residence/image-10.webp"
    ],
    "plans": [
      "/portfolio/taoyuan-residence/plan-01.webp"
    ],
    "heroImages": []
  },
  {
    "slug": "residence-2024",
    "name": "住宅",
    "year": 2024,
    "category": "residential",
    "cover": "/portfolio/residence-2024/cover.webp",
    "images": [
      "/portfolio/residence-2024/image-01.webp",
      "/portfolio/residence-2024/image-02.webp",
      "/portfolio/residence-2024/image-03.webp",
      "/portfolio/residence-2024/image-04.webp",
      "/portfolio/residence-2024/image-05.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "vanke-yuewan",
    "name": "万科悦湾",
    "year": 2023,
    "category": "residential",
    "cover": "/portfolio/vanke-yuewan/cover.webp",
    "images": [
      "/portfolio/vanke-yuewan/image-01.webp",
      "/portfolio/vanke-yuewan/image-02.webp",
      "/portfolio/vanke-yuewan/image-03.webp",
      "/portfolio/vanke-yuewan/image-04.webp",
      "/portfolio/vanke-yuewan/image-05.webp",
      "/portfolio/vanke-yuewan/image-06.webp",
      "/portfolio/vanke-yuewan/image-07.webp",
      "/portfolio/vanke-yuewan/image-08.webp",
      "/portfolio/vanke-yuewan/image-09.webp",
      "/portfolio/vanke-yuewan/image-10.webp"
    ],
    "plans": [
      "/portfolio/vanke-yuewan/plan-01.webp"
    ],
    "heroImages": []
  },
  {
    "slug": "lvdao-townhouse",
    "name": "莱芜·绿岛花园联排别墅",
    "year": 2019,
    "category": "residential",
    "cover": "/portfolio/lvdao-townhouse/cover.webp",
    "images": [
      "/portfolio/lvdao-townhouse/image-01.webp",
      "/portfolio/lvdao-townhouse/image-02.webp",
      "/portfolio/lvdao-townhouse/image-03.webp",
      "/portfolio/lvdao-townhouse/image-04.webp",
      "/portfolio/lvdao-townhouse/image-05.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "smart-medical-office",
    "name": "智慧医药",
    "year": 2024,
    "category": "office",
    "cover": "/portfolio/smart-medical-office/cover.webp",
    "images": [
      "/portfolio/smart-medical-office/image-01.webp",
      "/portfolio/smart-medical-office/image-02.webp",
      "/portfolio/smart-medical-office/image-03.webp",
      "/portfolio/smart-medical-office/image-04.webp",
      "/portfolio/smart-medical-office/image-05.webp",
      "/portfolio/smart-medical-office/image-06.webp",
      "/portfolio/smart-medical-office/image-07.webp",
      "/portfolio/smart-medical-office/image-08.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "jinxiao-office",
    "name": "重庆办公金消",
    "year": 2022,
    "category": "office",
    "cover": "/portfolio/jinxiao-office/cover.webp",
    "images": [
      "/portfolio/jinxiao-office/image-01.webp",
      "/portfolio/jinxiao-office/image-02.webp",
      "/portfolio/jinxiao-office/image-03.webp",
      "/portfolio/jinxiao-office/image-04.webp",
      "/portfolio/jinxiao-office/image-05.webp",
      "/portfolio/jinxiao-office/image-06.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "zhongsite-office",
    "name": "重庆中斯加特集团办公室",
    "year": 2020,
    "category": "office",
    "cover": "/portfolio/zhongsite-office/cover.webp",
    "images": [
      "/portfolio/zhongsite-office/image-01.webp",
      "/portfolio/zhongsite-office/image-02.webp",
      "/portfolio/zhongsite-office/image-03.webp",
      "/portfolio/zhongsite-office/image-04.webp",
      "/portfolio/zhongsite-office/image-05.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "hengshui-office",
    "name": "衡水研发办公楼",
    "year": 2020,
    "category": "office",
    "cover": "/portfolio/hengshui-office/cover.webp",
    "images": [
      "/portfolio/hengshui-office/image-01.webp",
      "/portfolio/hengshui-office/image-02.webp",
      "/portfolio/hengshui-office/image-03.webp",
      "/portfolio/hengshui-office/image-04.webp",
      "/portfolio/hengshui-office/image-05.webp",
      "/portfolio/hengshui-office/image-06.webp",
      "/portfolio/hengshui-office/image-07.webp",
      "/portfolio/hengshui-office/image-08.webp",
      "/portfolio/hengshui-office/image-09.webp",
      "/portfolio/hengshui-office/image-10.webp",
      "/portfolio/hengshui-office/image-11.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "majian-office",
    "name": "马健国际建筑设计办公室",
    "year": 2019,
    "category": "office",
    "cover": "/portfolio/majian-office/cover.webp",
    "images": [
      "/portfolio/majian-office/image-01.webp",
      "/portfolio/majian-office/image-02.webp",
      "/portfolio/majian-office/image-03.webp",
      "/portfolio/majian-office/image-04.webp",
      "/portfolio/majian-office/image-05.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "chongqing-spa",
    "name": "重庆 SPA会所",
    "year": 2025,
    "category": "commercial",
    "cover": "/portfolio/chongqing-spa/cover.webp",
    "images": [
      "/portfolio/chongqing-spa/image-01.webp",
      "/portfolio/chongqing-spa/image-02.webp",
      "/portfolio/chongqing-spa/image-03.webp",
      "/portfolio/chongqing-spa/image-04.webp",
      "/portfolio/chongqing-spa/image-05.webp",
      "/portfolio/chongqing-spa/image-06.webp",
      "/portfolio/chongqing-spa/image-07.webp",
      "/portfolio/chongqing-spa/image-08.webp",
      "/portfolio/chongqing-spa/image-09.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "indian-restaurant",
    "name": "印度餐厅",
    "year": 2025,
    "category": "commercial",
    "cover": "/portfolio/indian-restaurant/cover.webp",
    "images": [
      "/portfolio/indian-restaurant/image-01.webp",
      "/portfolio/indian-restaurant/image-02.webp",
      "/portfolio/indian-restaurant/image-03.webp",
      "/portfolio/indian-restaurant/image-04.webp",
      "/portfolio/indian-restaurant/image-05.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "artisan-barbershop",
    "name": "北京 匠人理发",
    "year": 2024,
    "category": "commercial",
    "cover": "/portfolio/artisan-barbershop/cover.webp",
    "images": [
      "/portfolio/artisan-barbershop/image-01.webp",
      "/portfolio/artisan-barbershop/image-02.webp",
      "/portfolio/artisan-barbershop/image-03.webp",
      "/portfolio/artisan-barbershop/image-04.webp",
      "/portfolio/artisan-barbershop/image-05.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "ruilibao-retail",
    "name": "重庆 瑞利宝",
    "year": 2023,
    "category": "commercial",
    "cover": "/portfolio/ruilibao-retail/cover.webp",
    "images": [
      "/portfolio/ruilibao-retail/image-01.webp",
      "/portfolio/ruilibao-retail/image-02.webp",
      "/portfolio/ruilibao-retail/image-03.webp",
      "/portfolio/ruilibao-retail/image-04.webp",
      "/portfolio/ruilibao-retail/image-05.webp",
      "/portfolio/ruilibao-retail/image-06.webp"
    ],
    "plans": [
      "/portfolio/ruilibao-retail/plan-01.webp"
    ],
    "heroImages": []
  },
  {
    "slug": "barbershop",
    "name": "理发店",
    "year": 2023,
    "category": "commercial",
    "cover": "/portfolio/barbershop/cover.webp",
    "images": [
      "/portfolio/barbershop/image-01.webp",
      "/portfolio/barbershop/image-02.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "xian-poly-sales-center",
    "name": "西安保利和光尘樾售房部",
    "year": 2020,
    "category": "commercial",
    "cover": "/portfolio/xian-poly-sales-center/cover.webp",
    "images": [
      "/portfolio/xian-poly-sales-center/image-01.webp",
      "/portfolio/xian-poly-sales-center/image-02.webp",
      "/portfolio/xian-poly-sales-center/image-03.webp",
      "/portfolio/xian-poly-sales-center/image-04.webp",
      "/portfolio/xian-poly-sales-center/image-05.webp",
      "/portfolio/xian-poly-sales-center/image-06.webp",
      "/portfolio/xian-poly-sales-center/image-07.webp",
      "/portfolio/xian-poly-sales-center/image-08.webp",
      "/portfolio/xian-poly-sales-center/image-09.webp",
      "/portfolio/xian-poly-sales-center/image-10.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "poly-pool-club",
    "name": "重庆.保利天汇泳池",
    "year": 2019,
    "category": "commercial",
    "cover": "/portfolio/poly-pool-club/cover.webp",
    "images": [
      "/portfolio/poly-pool-club/image-01.webp",
      "/portfolio/poly-pool-club/image-02.webp",
      "/portfolio/poly-pool-club/image-03.webp",
      "/portfolio/poly-pool-club/image-04.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "guiyang-shopping-center",
    "name": "贵阳保税区大数据购物中心",
    "year": 2019,
    "category": "commercial",
    "cover": "/portfolio/guiyang-shopping-center/cover.webp",
    "images": [
      "/portfolio/guiyang-shopping-center/image-01.webp",
      "/portfolio/guiyang-shopping-center/image-02.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "guotan-store",
    "name": "贵州国坛直营店",
    "year": 2019,
    "category": "commercial",
    "cover": "/portfolio/guotan-store/cover.webp",
    "images": [
      "/portfolio/guotan-store/image-01.webp",
      "/portfolio/guotan-store/image-02.webp",
      "/portfolio/guotan-store/image-03.webp",
      "/portfolio/guotan-store/image-04.webp",
      "/portfolio/guotan-store/image-05.webp",
      "/portfolio/guotan-store/image-06.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "love-valley-sales-center",
    "name": "重庆 爱情谷 销售中心",
    "year": 2018,
    "category": "commercial",
    "cover": "/portfolio/love-valley-sales-center/cover.webp",
    "images": [
      "/portfolio/love-valley-sales-center/image-01.webp",
      "/portfolio/love-valley-sales-center/image-02.webp",
      "/portfolio/love-valley-sales-center/image-03.webp",
      "/portfolio/love-valley-sales-center/image-04.webp",
      "/portfolio/love-valley-sales-center/image-05.webp",
      "/portfolio/love-valley-sales-center/image-06.webp",
      "/portfolio/love-valley-sales-center/image-07.webp",
      "/portfolio/love-valley-sales-center/image-08.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "tesla-showroom",
    "name": "特斯拉专卖店",
    "year": 2018,
    "category": "commercial",
    "cover": "/portfolio/tesla-showroom/cover.webp",
    "images": [
      "/portfolio/tesla-showroom/image-01.webp",
      "/portfolio/tesla-showroom/image-02.webp",
      "/portfolio/tesla-showroom/image-03.webp",
      "/portfolio/tesla-showroom/image-04.webp",
      "/portfolio/tesla-showroom/image-05.webp",
      "/portfolio/tesla-showroom/image-06.webp",
      "/portfolio/tesla-showroom/image-07.webp"
    ],
    "plans": [
      "/portfolio/tesla-showroom/plan-01.webp"
    ],
    "heroImages": []
  },
  {
    "slug": "qianfang-gallery",
    "name": "千方综合厅",
    "year": 2025,
    "category": "exhibition",
    "cover": "/portfolio/qianfang-gallery/cover.webp",
    "images": [
      "/portfolio/qianfang-gallery/image-01.webp",
      "/portfolio/qianfang-gallery/image-02.webp",
      "/portfolio/qianfang-gallery/image-03.webp",
      "/portfolio/qianfang-gallery/image-04.webp",
      "/portfolio/qianfang-gallery/image-05.webp",
      "/portfolio/qianfang-gallery/image-06.webp",
      "/portfolio/qianfang-gallery/image-07.webp",
      "/portfolio/qianfang-gallery/image-08.webp",
      "/portfolio/qianfang-gallery/image-09.webp",
      "/portfolio/qianfang-gallery/image-10.webp",
      "/portfolio/qianfang-gallery/image-11.webp",
      "/portfolio/qianfang-gallery/image-12.webp",
      "/portfolio/qianfang-gallery/image-13.webp",
      "/portfolio/qianfang-gallery/image-14.webp",
      "/portfolio/qianfang-gallery/image-15.webp",
      "/portfolio/qianfang-gallery/image-16.webp",
      "/portfolio/qianfang-gallery/image-17.webp",
      "/portfolio/qianfang-gallery/image-18.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "great-hall-gallery",
    "name": "重庆大礼堂展厅",
    "year": 2024,
    "category": "exhibition",
    "cover": "/portfolio/great-hall-gallery/cover.webp",
    "images": [
      "/portfolio/great-hall-gallery/image-01.webp",
      "/portfolio/great-hall-gallery/image-02.webp",
      "/portfolio/great-hall-gallery/image-03.webp",
      "/portfolio/great-hall-gallery/image-04.webp",
      "/portfolio/great-hall-gallery/image-05.webp",
      "/portfolio/great-hall-gallery/image-06.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "xiahao-gallery",
    "name": "下浩展厅",
    "year": 2024,
    "category": "exhibition",
    "cover": "/portfolio/xiahao-gallery/cover.webp",
    "images": [
      "/portfolio/xiahao-gallery/image-01.webp",
      "/portfolio/xiahao-gallery/image-02.webp",
      "/portfolio/xiahao-gallery/image-03.webp",
      "/portfolio/xiahao-gallery/image-04.webp",
      "/portfolio/xiahao-gallery/image-05.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "haikou-hotel",
    "name": "海口酒店",
    "year": 2025,
    "category": "hotel",
    "cover": "/portfolio/haikou-hotel/cover.webp",
    "images": [
      "/portfolio/haikou-hotel/image-01.webp",
      "/portfolio/haikou-hotel/image-02.webp",
      "/portfolio/haikou-hotel/image-03.webp",
      "/portfolio/haikou-hotel/image-04.webp",
      "/portfolio/haikou-hotel/image-05.webp",
      "/portfolio/haikou-hotel/image-06.webp",
      "/portfolio/haikou-hotel/image-07.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "sichuan-hotel",
    "name": "四川酒店",
    "year": 2025,
    "category": "hotel",
    "cover": "/portfolio/sichuan-hotel/cover.webp",
    "images": [
      "/portfolio/sichuan-hotel/image-01.webp",
      "/portfolio/sichuan-hotel/image-02.webp",
      "/portfolio/sichuan-hotel/image-03.webp",
      "/portfolio/sichuan-hotel/image-04.webp",
      "/portfolio/sichuan-hotel/image-05.webp",
      "/portfolio/sichuan-hotel/image-06.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "chengtuo-hotel",
    "name": "城拓酒店",
    "year": 2024,
    "category": "hotel",
    "cover": "/portfolio/chengtuo-hotel/cover.webp",
    "images": [
      "/portfolio/chengtuo-hotel/image-01.webp",
      "/portfolio/chengtuo-hotel/image-02.webp",
      "/portfolio/chengtuo-hotel/image-03.webp",
      "/portfolio/chengtuo-hotel/image-04.webp",
      "/portfolio/chengtuo-hotel/image-05.webp",
      "/portfolio/chengtuo-hotel/image-06.webp",
      "/portfolio/chengtuo-hotel/image-07.webp",
      "/portfolio/chengtuo-hotel/image-08.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "youyang-yuejianli",
    "name": "酉阳悦涧里民宿",
    "year": 2023,
    "category": "hotel",
    "cover": "/portfolio/youyang-yuejianli/cover.webp",
    "images": [
      "/portfolio/youyang-yuejianli/image-01.webp",
      "/portfolio/youyang-yuejianli/image-02.webp",
      "/portfolio/youyang-yuejianli/image-03.webp",
      "/portfolio/youyang-yuejianli/image-04.webp",
      "/portfolio/youyang-yuejianli/image-05.webp",
      "/portfolio/youyang-yuejianli/image-06.webp",
      "/portfolio/youyang-yuejianli/image-07.webp",
      "/portfolio/youyang-yuejianli/image-08.webp",
      "/portfolio/youyang-yuejianli/image-09.webp",
      "/portfolio/youyang-yuejianli/image-10.webp",
      "/portfolio/youyang-yuejianli/image-11.webp"
    ],
    "plans": [
      "/portfolio/youyang-yuejianli/plan-01.webp"
    ],
    "heroImages": []
  },
  {
    "slug": "qingai-wensu",
    "name": "青艾文宿",
    "year": 2022,
    "category": "hotel",
    "cover": "/portfolio/qingai-wensu/cover.webp",
    "images": [
      "/portfolio/qingai-wensu/image-01.webp",
      "/portfolio/qingai-wensu/image-02.webp",
      "/portfolio/qingai-wensu/image-03.webp",
      "/portfolio/qingai-wensu/image-04.webp",
      "/portfolio/qingai-wensu/image-05.webp",
      "/portfolio/qingai-wensu/image-06.webp",
      "/portfolio/qingai-wensu/image-07.webp",
      "/portfolio/qingai-wensu/image-08.webp",
      "/portfolio/qingai-wensu/image-09.webp",
      "/portfolio/qingai-wensu/image-10.webp",
      "/portfolio/qingai-wensu/image-11.webp"
    ],
    "plans": [
      "/portfolio/qingai-wensu/plan-01.webp"
    ],
    "heroImages": []
  },
  {
    "slug": "jinfoshan-lodge-chongqing",
    "name": "重庆 金佛山民宿",
    "year": 2020,
    "category": "hotel",
    "cover": "/portfolio/jinfoshan-lodge-chongqing/cover.webp",
    "images": [
      "/portfolio/jinfoshan-lodge-chongqing/image-01.webp",
      "/portfolio/jinfoshan-lodge-chongqing/image-02.webp",
      "/portfolio/jinfoshan-lodge-chongqing/image-03.webp",
      "/portfolio/jinfoshan-lodge-chongqing/image-04.webp",
      "/portfolio/jinfoshan-lodge-chongqing/image-05.webp",
      "/portfolio/jinfoshan-lodge-chongqing/image-06.webp",
      "/portfolio/jinfoshan-lodge-chongqing/image-07.webp",
      "/portfolio/jinfoshan-lodge-chongqing/image-08.webp",
      "/portfolio/jinfoshan-lodge-chongqing/image-09.webp",
      "/portfolio/jinfoshan-lodge-chongqing/image-10.webp",
      "/portfolio/jinfoshan-lodge-chongqing/image-11.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "jinfoshan-lodge",
    "name": "金佛山民宿",
    "year": 2020,
    "category": "hotel",
    "cover": "/portfolio/jinfoshan-lodge/cover.webp",
    "images": [
      "/portfolio/jinfoshan-lodge/image-01.webp",
      "/portfolio/jinfoshan-lodge/image-02.webp",
      "/portfolio/jinfoshan-lodge/image-03.webp",
      "/portfolio/jinfoshan-lodge/image-04.webp",
      "/portfolio/jinfoshan-lodge/image-05.webp",
      "/portfolio/jinfoshan-lodge/image-06.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "jiayu-hotel-renovation",
    "name": "重庆 佳宇英皇酒店改造",
    "year": 2019,
    "category": "hotel",
    "cover": "/portfolio/jiayu-hotel-renovation/cover.webp",
    "images": [
      "/portfolio/jiayu-hotel-renovation/image-01.webp",
      "/portfolio/jiayu-hotel-renovation/image-02.webp",
      "/portfolio/jiayu-hotel-renovation/image-03.webp",
      "/portfolio/jiayu-hotel-renovation/image-04.webp",
      "/portfolio/jiayu-hotel-renovation/image-05.webp",
      "/portfolio/jiayu-hotel-renovation/image-06.webp",
      "/portfolio/jiayu-hotel-renovation/image-07.webp",
      "/portfolio/jiayu-hotel-renovation/image-08.webp"
    ],
    "plans": [],
    "heroImages": []
  },
  {
    "slug": "tenglong-hotel",
    "name": "达州腾龙酒店",
    "year": 2019,
    "category": "hotel",
    "cover": "/portfolio/tenglong-hotel/cover.webp",
    "images": [
      "/portfolio/tenglong-hotel/image-01.webp",
      "/portfolio/tenglong-hotel/image-02.webp",
      "/portfolio/tenglong-hotel/image-03.webp",
      "/portfolio/tenglong-hotel/image-04.webp",
      "/portfolio/tenglong-hotel/image-05.webp",
      "/portfolio/tenglong-hotel/image-06.webp",
      "/portfolio/tenglong-hotel/image-07.webp"
    ],
    "plans": [],
    "heroImages": []
  }
];
